dist: bionic
language: python
group: edge
python: 3.8
os: linux

matrix:
  fast_finish: true
  # allow_failures:
  #   - env: DOCKER=archlinux-webengine-unstable QUTE_BDD_WEBENGINE=true
  #     services: docker
  include:
    ### Archlinux QtWebEngine with testing/KDE-Unstable
    - env: DOCKER=archlinux-webengine-unstable QUTE_BDD_WEBENGINE=true
      services: docker

    ### PyQt 5.15 (Python 3.8)
    - env: TESTENV=py38-pyqt515
      # http://code.qt.io/cgit/qt/qtbase.git/commit/?id=c3a963da1f9e7b1d37e63eedded61da4fbdaaf9a
      addons:
        apt:
          packages:
          - libxkbcommon-x11-0
          - libxcb-xkb1
          - libxcb-xinput0
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/build/qutebrowser/qutebrowser/.cache

install:
  - bash scripts/dev/ci/travis_install.sh
  - ulimit -c unlimited

script:
  - bash scripts/dev/ci/travis_run.sh

after_success:
  - '[[ $TESTENV == *-cov ]] && codecov -e TESTENV -X gcov'

after_failure:
  - bash scripts/dev/ci/travis_backtrace.sh
